version: "2"

services:

  camera_0:
    privileged: false  # true in example
    restart: always
    build: remote_devices/camera_0
    networks:
      - microscope_network

  light_0:
    privileged: false
    restart: always
    build: remote_devices/light_0
    networks:
      - microscope_network

  microscope_jupyter:
#    privileged: false
#    restart: always
    build: training_environments/remote_control
    networks:
      - microscope_network
    ports:
      - "8888:8888"

networks:
  microscope_network:
    name: microscope_network
#    driver: bridge
